exception: 'catched: divizion by zero'
finally...
no problems!
